#:schema node_modules/wrangler/config-schema.json
name = "durable-notifications"
main = "src/index.ts"
compatibility_date = "2024-11-12"
compatibility_flags = [ "nodejs_compat" ]

[observability]
enabled = true

[durable_objects]
bindings = [
  { name = "PREFERENCES", class_name = "PreferenceManager" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["PreferenceManager"]

[[rules]] 
type = "Text"
globs = ["**/*.sql"]
fallthrough = true